/**
 * @file font.h
 * @brief A glyph table generated by tools/glyphs.html (TSGL format).
 *
 * Glyphs are rotated once when loaded, so a glyph can be copied straight
 * into a panel-oriented buffer. cell_w/cell_h are the cell as the user
 * sees it; glyph_w/glyph_h are the rotated bitmap's dimensions.
 *
 * File layout (little-endian):
 * @code
 *   offset  size  field
 *   0       4     magic "TSGL"
 *   4       2     format version, 1
 *   6       2     cell width in pixels
 *   8       2     cell height in pixels
 *   10      2     reserved
 *   12      4     glyph count
 *   16      ...   glyphs: u32 codepoint, then width*height bytes,
 *                 0x00 black / 0xF0 white, ascending by codepoint
 * @endcode
 */
#ifndef FONT_H
#define FONT_H

#include <stdint.h>

/** A loaded, rotated glyph table. */
typedef struct {
    int cell_w, cell_h;     /**< Cell size in the user's orientation. */
    int glyph_w, glyph_h;   /**< Bitmap size after rotation. */
    uint32_t count;
    uint32_t *codepoints;   /**< Ascending; binary-searched. */
    uint8_t *bitmaps;       /**< count * glyph_w * glyph_h. */
    uint8_t *missing;       /**< Drawn for codepoints not in the table. */
} font_t;

/**
 * @brief Load a table and rotate every glyph.
 * @param f        The font to fill in.
 * @param path     A .bin file from tools/glyphs.html.
 * @param rotation 0, 90, 180 or 270 — the same value the canvas uses.
 * @return 0 on success, -1 on failure (message on stderr).
 */
int font_load(font_t *f, const char *path, int rotation);

/** @brief Free the table. */
void font_free(font_t *f);

/**
 * @brief The rotated bitmap for a codepoint.
 * @return glyph_w * glyph_h bytes, the missing-glyph box for unknown
 *         codepoints, or NULL for codepoints that draw nothing (space
 *         and control characters).
 */
const uint8_t *font_glyph(const font_t *f, uint32_t cp);

#endif
